sudo: required
dist: trust
language: node_js
node_js:
  - "0.10"
  - "4"
  - "5"
  - "6"
  - "7"
cache:
  - "node_modules"
install:
  - "npm install"
before_script:
  - "npm install -g backed-cli"
  - "backed -b"
script:
  - "npm run test"
